import Translator from "../../../resources/localization/translator";

export const LocalizedString = language => {
	return {
		// SELECT_VIDEO_SOURCE: Translator.translate("SELECT_VIDEO_SOURCE", language),
		SELECT_VIDEO_SOURCE: "Chọn nguồn video",
		// SELECT_INPUT_AUDIO_SOURCE: Translator.translate("SELECT_INPUT_AUDIO_SOURCE", language),
		SELECT_INPUT_AUDIO_SOURCE: "Chọn thiết bị audio đầu vào",
		// SELECT_OUTPUT_AUDIO_SOURCE: Translator.translate("SELECT_OUTPUT_AUDIO_SOURCE", language),
		SELECT_OUTPUT_AUDIO_SOURCE: "Chọn thiết bị audio đầu ra",
		// SELECT_MODE: Translator.translate("SELECT_MODE", language),
		SELECT_MODE: "Chọn chế độ",
		// CALL_RECORDING_STARTED_MSG: Translator.translate("CALL_RECORDING_STARTED_MSG", language),
		CALL_RECORDING_STARTED_MSG: "Đã ghi lại cuộc gọi",
		// USER_JOINED_CALL_MSG: Translator.translate("USER_JOINED_CALL_MSG", language),
		USER_JOINED_CALL_MSG: "Người dùng đã tham gia cuộc gọi",
		// CALL_RECORDING_ENDED_MSG: Translator.translate("CALL_RECORDING_ENDED_MSG", language),
		CALL_RECORDING_ENDED_MSG: "Kết thúc ghi lại cuộc gọi",
		// USER_LEFT_CALL_MSG: Translator.translate("USER_LEFT_CALL_MSG", language),
		USER_LEFT_CALL_MSG: "Người dùng đã rời khỏi cuộc gọi",
		// CAMERA_ERROR_MSG: Translator.translate("CAMERA_ERROR_MSG", language),
		CAMERA_ERROR_MSG: "Lỗi camera",
		// MIC_ERROR_MSG: Translator.translate("MIC_ERROR_MSG", language),
		MIC_ERROR_MSG: "Lỗi mic",
		// CAMERA_MIC_ERROR_MSG: Translator.translate("CAMERA_MIC_ERROR_MSG", language),
		CAMERA_MIC_ERROR_MSG: "Lỗi camera hoặc mic",
		// RECORDING_TEXT: Translator.translate("RECORDING_TEXT", language),
		RECORDING_TEXT: "Đang ghi lại cuộc gọi",
		TRYING_TO_START_RECORDING_TEXT: Translator.translate("TRYING_TO_START_RECORDING_TEXT", language),
		// JOINING_TEXT: Translator.translate("JOINING_TEXT", language),
		JOINING_TEXT: "Đang kết nối",
		// UN_MUTE_AUDIO_TEXT: Translator.translate("UN_MUTE_AUDIO_TEXT", language),
		UN_MUTE_AUDIO_TEXT: "Bỏ tắt tiếng",
		// MUTE_AUDIO_TEXT: Translator.translate("MUTE_AUDIO_TEXT", language),
		MUTE_AUDIO_TEXT: "Tắt tiếng",
		// END_CALL_TEXT: Translator.translate("END_CALL_TEXT", language),
		END_CALL_TEXT: "Kết thúc cuộc gọi",
		// START_RECORDING_TEXT: Translator.translate("START_RECORDING_TEXT", language),
		START_RECORDING_TEXT: "Ghi lại cuộc gọi",
		// STOP_RECORDING_TEXT: Translator.translate("STOP_RECORDING_TEXT", language),
		STOP_RECORDING_TEXT: "Dừng ghi cuộc gọi",
		// START_SCREEN_SHARE_TEXT: Translator.translate("START_SCREEN_SHARE_TEXT", language),
		START_SCREEN_SHARE_TEXT: "Chia sẻ màn hình",
		// STOP_SCREEN_SHARE_TEXT: Translator.translate("STOP_SCREEN_SHARE_TEXT", language),
		STOP_SCREEN_SHARE_TEXT: "Dừng chi sẻ màn hình",
		// MUTE_VIDEO_TEXT: Translator.translate("MUTE_VIDEO_TEXT", language),
		MUTE_VIDEO_TEXT: "Tắt tiếng video",
		// UN_MUTE_VIDEO_TEXT: Translator.translate("UN_MUTE_VIDEO_TEXT", language),
		UN_MUTE_VIDEO_TEXT: "Bỏ tắt tiếng video",
		// SELECT_LAYOUT_HEADER: Translator.translate("SELECT_LAYOUT_HEADER", language),
		SELECT_LAYOUT_HEADER: "Chọn kiểu hiển thị",
		NO_OF_USER_IN_TILE_TEXT: Translator.translate("NO_OF_USER_IN_TILE_TEXT", language),
		// CHANGE_AUDIO_SOURCE: Translator.translate("CHANGE_AUDIO_SOURCE", language),
		CHANGE_AUDIO_SOURCE: "Thay đổi nguồn audio",
		// CHANGE_AUDIO_SOURCE_DESC: Translator.translate("CHANGE_AUDIO_SOURCE_DESC", language),
		CHANGE_AUDIO_SOURCE_DESC: "Bạn có thể chọn đầu vào và đầu ra âm thanh mong muốn",
		// AUDIO_INPUT_DEVICE_LABEL: Translator.translate("AUDIO_INPUT_DEVICE_LABEL", language),
		AUDIO_INPUT_DEVICE_LABEL: "Lựa chọn nguồn audio",
		// NO_AUDIO_DEVICE_AVAILABLE: Translator.translate("NO_AUDIO_DEVICE_AVAILABLE", language),
		NO_AUDIO_DEVICE_AVAILABLE: "Không có thiết bị audio nào",
		// AUDIO_OUTPUT_DEVICE_LABEL: Translator.translate("AUDIO_OUTPUT_DEVICE_LABEL", language),
		AUDIO_OUTPUT_DEVICE_LABEL: "Lựa chọn đầu ra audio",
		// CHANGE_VIDEO_SOURCE: Translator.translate("CHANGE_VIDEO_SOURCE", language),
		CHANGE_VIDEO_SOURCE: "Thay đổi nguồn video",
		// CHANGE_VIDEO_SOURCE_DESC: Translator.translate("CHANGE_VIDEO_SOURCE_DESC", language),
		CHANGE_VIDEO_SOURCE_DESC: "Bạn có thể chọn thiết bị video mong muốn",
		// VIDEO_DEVICES_LABEL: Translator.translate("VIDEO_DEVICES_LABEL", language),
		VIDEO_DEVICES_LABEL: "Thay đổi nguồn video",
		// FULL_SCREEN: Translator.translate("FULL_SCREEN", language),
		FULL_SCREEN: "Toàn màn hình",
		// EXIT_FULL_SCREEN: Translator.translate("EXIT_FULL_SCREEN", language),
		EXIT_FULL_SCREEN: "Thoát toàn màn hình",
		// CHANGE_LAYOUT: Translator.translate("CHANGE_LAYOUT", language),
		CHANGE_LAYOUT: "Thay đổi kiểu hiển thị",
		// AUDIO_SETTING: Translator.translate("AUDIO_SETTING", language),
		AUDIO_SETTING: "Cài đặt âm thanh",
		// VIDEO_SETTING: Translator.translate("VIDEO_SETTING", language),
		VIDEO_SETTING: "Cài đặt video",
		// USER_LIST: Translator.translate("USER_LIST", language),
		USER_LIST: "Danh sách người dùng",
		// MORE: Translator.translate("MORE", language),
		MORE: "Thêm",
		// MUTE_USER: Translator.translate("MUTE_USER", language),
		MUTE_USER: "Tắt tiếng người dùng này",
		// PIN_USER: Translator.translate("PIN_USER", language),
		PIN_USER: "Ghim người dùng này",
		// UNPIN_USER: Translator.translate("UNPIN_USER", language),
		UNPIN_USER: "Bỏ ghim người dùng này",
		// UN_MUTE_USER: Translator.translate("UN_MUTE_USER", language),
		UN_MUTE_USER: "Bỏ tắt tiếng người dùng này",
		// MUTED: Translator.translate("MUTED", language),
		MUTED: "Đã tắt tiếng",
		// YOU_HAVE_BLOCKED: Translator.translate("YOU_HAVE_BLOCKED", language),
		YOU_HAVE_BLOCKED: "Bạn đã bị chặn",
		// NOT_POSSIBLE_TO_SEND_MESSAGES: Translator.translate("NOT_POSSIBLE_TO_SEND_MESSAGES", language),
		NOT_POSSIBLE_TO_SEND_MESSAGES: "Không thể gửi tin nhắn",
		IOS_BROWSER_WARNING: Translator.translate("IOS_BROWSER_WARNING", language),
		PEOPLE_TEXT: Translator.translate("PEOPLE_TEXT", language),
		SPOTLIGHT_DETAIL_TEXT1: Translator.translate("SPOTLIGHT_DETAIL_TEXT1", language),
		SPOTLIGHT_DETAIL_TEXT2: Translator.translate("SPOTLIGHT_DETAIL_TEXT2", language),
		SPOTLIGHT_DETAIL_TEXT3: Translator.translate("SPOTLIGHT_DETAIL_TEXT3", language),
		SPOTLIGHT_DETAIL_TEXT4: Translator.translate("SPOTLIGHT_DETAIL_TEXT4", language),
	};
};
